### PR TITLE
Add Battle Chopper/Mr. Heli [WIP]

### PR DESCRIPTION
**Pull request by marchah**
## Battle Chopper / Mr. HELI no Daibouken

http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=bchopper

https://www.arcade-museum.com/game_detail.php?game_id=8777

bchopper

## Cocktail

Checking MAME source code it look like it doesn't support `cocktail`

```
GAME( 1987, bchopper,    0,        m72,          bchopper,     m72_state, init_bchopper,   ROT0,   "Irem", "Battle Chopper (World)", MACHINE_NO_COCKTAIL | MACHINE_SUPPORTS_SAVE )
GAME( 1987, mrheli,      bchopper, mrheli,       bchopper,     m72_state, init_m72_8751,   ROT0,   "Irem", "Mr. HELI no Daibouken (Japan)", MACHINE_NO_COCKTAIL | MACHINE_SUPPORTS_SAVE )
```

## TODO

- Do more search on [Mr. Heli](https://en.wikipedia.org/wiki/Mr._Heli) to hopefully find a picture of the arcade to get the buttons colors.
- What is `tilt` ?
- Not sure about `mirrored` and `cocktail`
- Japanese rom is called `mrheli`

### CODE REVIEW

**Comment by kpshek** [comment]
Thanks so much for the contribution @marchah! Let me know when this PR is ready for a review.

**Comment by marchah** [comment]
@kpshek do you know a way to find about `tilt`, `mirrored` and `cocktail` ? If i can't find infos about it should i put `0`?

I'm not able to find any pictures for this arcade cabinet, so i think i will put `Red` and `Blue` and add a comment in `miscDetails` to explain that the colors are arbitrary, is that ok?

**Comment by marchah** [comment]
@kpshek another question do you prefere a lot of small PRs or a big one?

I personally prefere a lot of small one as i find it not blocking if a game config is not perfect but after you're the one who will get spam by emails.

**Comment by mschoen79** [comment]
Is this project dead? My pull request is still listed...

**Comment by marchah** [comment]
mine is up to date but yea would be better if it get merged as this repo is the one listed in LEDBlinky doc

https://github.com/marchah/ledblinky-controls-colors

**Comment by kpshek** [comment]
Sorry for such a long delay @marchah! Thank you for the PR!

**Comment by mschoen79** [comment]
Alright!!! Im excited this is getting some attention!

**Pull request merged**
